version: '3.8'

services:
  ubuntu-agent:
    build: .  # Your agent's Dockerfile in ./agent folder
    container_name: ubuntu-ansible-agent-node
    image: ubuntu-ansible-agent-node-image:latest
    ports:
      - "2224:22"
      - "8083:80"
    environment:
      - MY_ENV=agent
    stdin_open: true
    tty: true
    networks:
      - jenkins_bridge

networks:
  jenkins_bridge:
    external: true
